# this file is to be kept up-to-date with the one in the operator-scorecard-test-container,
# as documented in the readme for this role
kind: Configuration
apiversion: scorecard.operatorframework.io/v1alpha3
metadata:
  name: config
stages:
  - parallel: true
    tests:
      - image: quay.io/operator-framework/scorecard-test@sha256:981e2acb40b53954a7daadbe1114af1faaa51a632cf7654765252124e50d7c7d
        entrypoint:
          - scorecard-test
          - basic-check-spec
        labels:
          suite: basic
          test: basic-check-spec-test
      - image: quay.io/operator-framework/scorecard-test@sha256:981e2acb40b53954a7daadbe1114af1faaa51a632cf7654765252124e50d7c7d
        entrypoint:
          - scorecard-test
          - olm-bundle-validation
        labels:
          suite: olm
          test: olm-bundle-validation-test
