---
- name: "Ensure the work_dir exists"
  file:
    path: "{{ work_dir }}"
    state: directory

- name: "Remove any previous validation results"
  shell: "rm -f {{ work_dir }}/validation-*"

- name: "Output the operator-sdk version"
  shell: "{{ operator_sdk_bin_path }} version"
  register: sdk_version_result

- name: "Output the operator-sdk version to a debug file"
  copy:
    content: "{{ sdk_version_result.stdout }}"
    dest: "{{ work_dir }}/validation-version.txt"
    mode: 0644
  when: sdk_version_result.stdout is defined

- name: "Set bundle_validate variable"
  set_fact:
    bundle_validate: "{{ bundle_image }}"
  when: run_upstream|bool

- name: "Set bundle_validate variable"
  set_fact:
    bundle_validate: "{{ operator_work_dir }}"
  when: not run_upstream|bool

- name: "Set the operatorhub checks if enabled"
  set_fact:
    select_optional_tests: "--select-optional name=operatorhub"
  when: run_operatorhub_checks|bool

- name: "Validate the operator bundle manifest and metadata with operator-sdk bundle validate"
  shell: "{{ operator_sdk_bin_path }} bundle validate {{ select_optional_tests }} --verbose {{ bundle_validate }} 2>&1"
  register: sdk_validation_result
  ignore_errors: true

- name: "Output the return code of operator-sdk bundle validate command to a debug file"
  copy:
    content: "{{ sdk_validation_result.rc }}"
    dest: "{{ work_dir }}/validation-rc.txt"
    mode: 0644
  when: sdk_validation_result.rc is defined

- name: "Output the result of operator-sdk bundle validate command to a debug file"
  copy:
    content: "{{ sdk_validation_result.stdout }}"
    dest: "{{ work_dir }}/validation-output.txt"
    mode: 0644
  when: sdk_validation_result.stdout is defined

- name: "Display the validation results"
  debug:
    msg: "Operator sdk validation output:\n {{ sdk_validation_result.stdout_lines }}"

- name: "Fail if the operator didn't satisfy the operator-sdk validation test"
  fail:
    msg: 'Operator sdk validation test failed, check validation-output.txt for more details'
  when:
    - check_validation_result|bool
    - sdk_validation_result.rc != 0
